# Generated by Django 2.0.5 on 2018-08-06 16:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_events_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 6, 16, 48, 4, 182796, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 6, 16, 48, 4, 182796, tzinfo=utc)),
        ),
    ]
