# Generated by Django 2.0.5 on 2018-08-06 16:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20180806_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='last_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 6, 16, 57, 19, 35143, tzinfo=utc)),
        ),
    ]
