# Generated by Django 2.0.5 on 2018-08-11 17:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20180806_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 11, 17, 40, 46, 571244, tzinfo=utc)),
        ),
    ]
