# Generated by Django 2.0.5 on 2018-08-17 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0006_auto_20180817_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desciption', models.TextField(max_length=400)),
                ('link', models.URLField(unique=True)),
                ('pic', models.ImageField(blank=True, upload_to='uploads')),
                ('published', models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 17, 15, 49, 54, 195923, tzinfo=utc))),
                ('last_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
